# /docker-compose.yml
version: '3.9'

services:
  backend:
    build: ./backend
    environment:
      - POSTGRES_IP=${POSTGRES_IP}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    depends_on:
      - database
    ports:
      - "8080:8080"

  frontend:
    build: ./react_app
    depends_on:
      - backend
    ports:
      - "3000:80"

  database:
    image: postgres
    hostname: "localhost"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"