# /docker-compose.yml
version: '3.9'

services:
  backend:
    build: ./backend
    depends_on:
      - database
    ports:
      - "8000:8000"

  frontend:
    build: ./react_app
    ports:
      - "3000:80"

  database:
    image: postgres
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    hostname: "localhost"
    ports:
      - "5432:5432"